apiVersion: serving.knative.dev/v1 
kind: Service
metadata:
  name: sleeptalker
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containerConcurrency: 5
      containers:
        - image: ko://github.com/psschwei/sleeptalker
          readinessProbe:
            periodSeconds: 0 # opt out of aggressive probing

